version: '3.7'
services:
    php:
        volumes:
            # To optimize loading of vendor for mac os and windows keep it inside the container
            - php_vendor:/usr/src/backend/vendor
    react:
        volumes:
            # To optimize loading of node_modules for mac os and windows keep it inside the container
            - node_modules:/usr/src/frontend/node_modules
volumes:
    php_vendor:
    node_modules:
