version: '3.7'
services:
    php:
        volumes:
            - './apps/backend/:/usr/src/backend'
        # comment this if not using sudo
        user: ${LOCAL_USER}
    nginx:
        volumes:
            - './apps/backend/public/:/usr/src/backend'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
    adminer:
        ports:
            - '${ADMINER_PORT}:8080'
    react:
        volumes:
            - './apps/frontend:/usr/src/frontend'
            # Uncomment this to share the node_modules with the filesystem
            # It is quiet slow so prefer keeping commented and install node_modules locally (outside docker) to have type hinting.
            #- './apps/frontend/node_modules:/usr/src/frontend/node_modules'
        ports:
            - '${REACT_PORT}:3000'
