version: '3.7'
services:
    php:
        volumes:
            - './apps/backend/:/usr/src/backend'
    nginx:
        volumes:
            - './apps/backend/public/:/usr/src/backend'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
    adminer:
        ports:
            - '${ADMINER_PORT}:8080'
    react:
        volumes:
            - './apps/frontend:/usr/src/frontend'
            - '/usr/src/frontend/node_modules'
        ports:
            - '${REACT_PORT}:3000'