version: '3.7'
services:
    mysql:
        container_name: database
        image: mysql:8.0
        restart: on-failure
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        env_file:
            - .env
        ports:
        - '4306:3306'
        volumes:
        - ./mysql:/var/lib/mysql
    adminer:
        image: adminer:latest
        restart: on-failure
        environment:
            ADMINER_DEFAULT_SERVER: 'mysql'
        depends_on:
            - mysql
        ports:
            - '${ADMINER_PORT}:8080'
    nginx:
        image: nginx:alpine
        restart: on-failure
        depends_on:
            - php
        volumes:
            - './apps/backend/public/:/usr/src/backend/public'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
    php:
        image: ${DOCKER_PHP_IMAGE}
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            cache_from:
                - ${DOCKER_PHP_IMAGE}
        restart: on-failure
        env_file:
            - .env
        depends_on:
            - mysql
        volumes:
            - './apps/backend/:/usr/src/backend'
    react:
        stdin_open: true
        tty: true
        image: ${DOCKER_NODE_IMAGE}
        build:
            context: .
            dockerfile: docker/react/Dockerfile
            cache_from:
                - ${DOCKER_NODE_IMAGE}
        env_file:
            - .env
        volumes:
            - './apps/frontend:/usr/src/frontend'
        ports:
            - '${REACT_PORT}:3000'
